name: Production CI/CD

on:
  push:
    branches:
      - main
      - update
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Production build
        run:  |
          make build-github-pages
          ls -la ./docs/* && git status

      - name: Commit build to prod branch
        run: |
          ls -la ./docs/* && git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          mv docs docs-tmp

          echo 'docs-tmp ...'
          ls -la ./docs-tmp/* && git status

          git checkout -f prod
          rm -rf docs/
          mv docs-tmp docs

          echo 'docs ...'
          ls -la ./docs/* && git status

          git add docs/
          git commit -m "generated docs based on commit to main branch"
          git push
